<!DOCTYPE html>
<title>Canvas test: 2d.imageData.object.ctor</title>
<script src="../tests.js"></script>
<link rel="stylesheet" href="../tests.css">
<link rel="prev" href="2d.imageData.object.readonly.html" title="2d.imageData.object.readonly">
<link rel="next" href="2d.imageData.object.set.html" title="2d.imageData.object.set">
<body class="show_output">
<p>
 <a href="2d.imageData.object.readonly.html" accesskey="p" title="[p] 2d.imageData.object.readonly">&lt;</a>
 <a href="index.html">[index]</a>
 <a href="2d.imageData.object.set.html" accesskey="n" title="[n] 2d.imageData.object.set">&gt;</a>
<h1><a href="index.2d.html">2d</a>.<a href="index.2d.imageData.html">imageData</a>.<a href="index.2d.imageData.object.html">object</a>.ctor</h1>
<p class="desc">ImageData does not have a usable constructor</p>
<div class="refs">References:
<ul>
<li><a href="spec.html#testrefs.2d.imageData.type">2d.imageData.type</a>

</ul>
</div>

<p class="output">Actual output:</p>
<canvas id="c" class="output" width="100" height="50"><p class="fallback">FAIL (fallback content)</p></canvas>

<ul id="d"></ul>
<script>
_addTest(function(canvas, ctx) {

_assertDifferent(window.ImageData, undefined, "window.ImageData", "undefined");
try { var _thrown = false; new window.ImageData(1,1); } catch (e) { _thrown = true; } finally { _assert(_thrown, "should throw exception: new window.ImageData(1,1)"); }


});
</script>

